# TODO: Create your Kivy layout in the kv language here
BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.3
        Label:
            text: 'Sort by'
        Spinner:
            id: sort_by
            text_autoupdate: True
            values: app.sort_keys
            on_text: app.sort_by(self.text)
        Label:
            text: 'Add New Song..'
        Label:
            text: 'Title:'
        TextInput:
            id: input_title
            text: ''
            multiline: False
            write_tab: False
        Label:
            text: 'Artist:'
        TextInput:
            id: input_artist
            text: ''
            multiline: False
            write_tab: False
        Label:
            text: 'Year:'
        TextInput:
            id: input_year
            text: ''
            multiline: False
            write_tab: False
        Button:
            text: 'Add Song'
            on_press: app.add_song()
        Button:
            text: 'Clear'
            on_press: app.clear_fields()
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: learned_text
            size_hint_y: 0.09
        BoxLayout:
            orientation: 'vertical'
            id: songs_list
        Label:
            id: warning_text
            text: ''
            size_hint_y: 0.09